### ISSUE TITLE
Wrong translation to Dutch

### ISSUE THREAD

**Issue by SamOtten** [duckduckgo/duckduckgo-locales#124]
I don't know if this is the right place to post this but there's a wrong translation on the Dutch version of DDG. Safe Search: off is translated to Veilig Zoeken: af, "af" means off as in 'get off the couch'. It should be translated to 'uit' which fits in this context better.

**Comment by jbarrett** [comment]
Hi @SamOtten! Can you verify this is resolved? Thanks!

**Comment by SamOtten** [comment]
It has been resolved!
