### ISSUE TITLE
Hardly any translation in Hindi

### ISSUE THREAD

**Issue by Rishabhbhat** [duckduckgo/duckduckgo-locales#173]
Hi, I'm new here and decided to help translating Duckduckgo . However, I noticed that there's **hardly** any translation in the Hindi version of Duckduckgo - for example, instead of _maps_ , it should be नक्शा.

**Comment by soumendrak** [comment]
@Rishabhbhat, You can start contributing. A lot of scope.

**Comment by Rishabhbhat** [comment]
Thanks, it's hard. Can't find the PO files anywhere.

    On Saturday, 7 September, 2019, 12:52:11 pm IST, Soumendra kumar sahoo <notifications@github.com> wrote:  
 
 
@Rishabhbhat, You can start contributing. A lot of scope.
