### ISSUE TITLE
Romanian translation

### ISSUE THREAD

**Issue by alexei** [duckduckgo/duckduckgo-locales#19]
There are a couple of issues with the Romanian translation:

### Diacritics
The Romanian language uses diacritics, yet not all of the translated words have them and those that do, use an incorrect style.

### Formal vs informal
Another thing I'd like to point out is the use of pronouns: the translation contains a mix of both personal pronouns and polite personal pronouns (that, or verbs in second person plural form). In practice, apps use one or the other e.g. Google mixes the two, while Apple uses an informal style. Personally, I'm in favor for the informal style. See also https://en.wikipedia.org/wiki/T–V_distinction

### Neologisms and loanwords
The word "browser", for example, is translated as both "browser" and "navigator". The word "navigator" refers to a person who navigates and I've never heard anyone calling a browser a "navigator". There are people who insist that we translate all words to Romanian, however words in the Romanian language were/are to a large extent borrowed from other languages see https://en.wikipedia.org/wiki/Romanian_language So in practice, romanians use the word "browser" even though it doesn't exist in the dictionary. And they do so with many other english words (e.g. "share", "like", "smiley face" etc.) even though some of them have a Romanian equivalent.
Another thing to point out here is the use of hyphens e.g. "browser-ul" ("the browser"). The norm is to discard the hyphen when the termination exists in the Romanian alphabet, but keep it when the last syllable has a different pronunciation e.g. "clickuri" ("clicks"), "boardul" ("the board"), "show-ul" ("the show")

Are there any guidelines in this regard?

I might be able to help with correcting diacritics, fixing some of the translations i.e. to use an informal style and common loanwords. What are your thoughts on this?

**Comment by jbarrett** [comment]
@alexei If you are available to contribute corrections, that would really be appreciated!

We don't (currently) have guidelines, but as they are developed they will likely be inspired by contributions like this issue.

I don't have specific context for Romanian, but I agree with your assessment. We should lean toward an informal style where appropriate (though not irreverent or jocular unless explicitly called for - privacy is a serious issue!)

If a loanword is makes a more elegant or easily understood translation than the precise formal version then we should probably use it.

Thanks!

**Comment by alexei** [comment]
I fixed most of the issues I pointed out so I think we can close this.

**Comment by jbarrett** [comment]
:+1: Thanks again @alexei!
