### ISSUE TITLE
Error in Greek translation

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/duckduckgo-locales#242]
From Petros on Twitter:

_The greek translation of "We dont go after you with ads" is wrong. It's supposed to be "Δεν σας κυνηγάμε με διαφημίσεις"_

https://twitter.com/Petros11888/status/1216747859757993984

**Comment by gaweki** [comment]
this hav been fixed in [here](https://github.com/duckduckgo/duckduckgo-locales/blob/master/locales/el_GR/LC_MESSAGES/duckduckgo.po)

**Comment by GioSensation** [comment]
The issue is fixed, so I'm closing this. Thanks!
