### ISSUE TITLE
Locale mix when browser is in kabyle language

### ISSUE THREAD

**Issue by BoFFire** [duckduckgo/duckduckgo-locales#264]
Hi,
When I use Firefox in kabyle/taqbaylit language, DuckDuckGo displays the page in `ka_GE` instead of `kab` or `kab_DZ`; I'm working on this issue.
Regards,

**Comment by BoFFire** [comment]
First shot : https://github.com/duckduckgo/duckduckgo-locales/pull/265
Comming next : translation of the main LC_MESSAGES

**Comment by BoFFire** [comment]
Updated : ref. PR https://github.com/duckduckgo/duckduckgo-locales/pull/267

**Comment by GioSensation** [comment]
The related PR was merged a while ago, so I am closing this issue. Thanks for your contribution, @BoFFire!
