### ISSUE TITLE
Missing placeholder?

### ISSUE THREAD

**Issue by etgocode** [duckduckgo/duckduckgo-locales#343]
The message
https://github.com/duckduckgo/duckduckgo-locales/blob/5a9871b4fa640170d858b4e110442e527b593e42/locales/de_DE/LC_MESSAGES/duckduckgo.po#L1825
seems to be intended to be placed next to a variable (the reason why the changes were made). However, there is no `%s`.
This may work for english but i.e. in german, the variable will most likely **not** be at the end. This makes a translation impossible at this moment (at least into german).

**Comment by GioSensation** [comment]
Hi @etgocode. Thanks for pointing this out. I reached out to a German speaking colleague at DDG and he suggested using a colon as a "language hack", something like `Bei Öffnungszeiten nicht in Betracht gezogen: Änderungen aufgrund ...`.

He says this workaround should get us there for this string, but in the future we will be more careful and always include the placeholder in the string.

Thanks again for getting in touch! 💪
