### ISSUE TITLE
There is no Ukraine region in the search engine settings!!!

### ISSUE THREAD

**Issue by bigvovan** [duckduckgo/duckduckgo-locales#344]
There is no Ukraine region in the search engine settings !!!
From the beginning of its launch, the region of Ukraine is absent from the search engine settings !!! I thought it would be corrected soon, because the Ukrainian language had already been added. But unfortunately the situation does not change. I ask the help of administrators.

**Comment by a-polivanchuk** [comment]
I agree! It is the main obstacle which prevents me from using DuckDuckGo search most of the time. It would be great to have the Ukraine added to the available regions.

**Comment by tagawa** [comment]
Thanks for reporting this. There are several regions we don't currently support for search results. Regarding Ukraine in particular I've forwarded your comments to the developers so they're aware.

**Comment by bigvovan** [comment]
> Thanks for reporting this. There are several regions we don't currently support for search results. Regarding Ukraine in particular I've forwarded your comments to the developers so they're aware.

It is very strange. You have a huge list of countries / regions that your search engine supports. But to add Ukraine, more than a year, some difficulties. Weird!

**Comment by bigvovan** [comment]
I don’t understand why Ukraine is in no hurry to add ??? After all, the big one is strange, there are a lot of active users, developers, gamers. The Ukrainian section of Wikipedia is included in the TOP 17 Wikipedia of the world.

**Comment by bigvovan** [comment]
A month has passed. The situation has not changed. Is it difficult to add Ukraine to the list ???

**Comment by a-polivanchuk** [comment]
I see the Ukraine is now available among regions. Thank you for the agile response to our request.
Will be testing it out from now!

**Comment by tagawa** [comment]
Hi @a-polivanchuk. Thanks for noticing and you're welcome! Sorry it took a while but it should work for you now.
