### ISSUE TITLE
Why are there such cardinal differences in the two language versions of the site?!

### ISSUE THREAD

**Issue by bigvovan** [duckduckgo/duckduckgo-locales#345]
Why are there such differences in the two language versions of the main page of the site ?!
I am adding two screenshots from the English version and the Ukrainian version of the site. This is also in other language versions of the site.
![DuckDuckGo English](https://user-images.githubusercontent.com/7887236/86764739-f34c4500-c050-11ea-9dad-7c9e37c3a8cb.png)
![DuckDuckGo Ukrainian](https://user-images.githubusercontent.com/7887236/86765033-48885680-c051-11ea-9282-b1ced177cbd2.png)

**Comment by GioSensation** [comment]
Hi @bigvovan. Thanks for reaching out. We're currently working on changes to the homepage to make it easier for people to learn about our other privacy products (not just search). We tend to roll these changes out gradually so we can look for users feedback and potential issues. Currently the new version is shown to a handful of countries and, if all goes well, we'll implement it for all countries later.

I hope this helps. If you have other questions, you can reply here or reach out to us over social networks.

Thanks again for your feedback and have a great day!
