### ISSUE TITLE
Lots of Czech strings are in Danish language

### ISSUE THREAD

**Issue by smuuf** [duckduckgo/duckduckgo-locales#413]
Seems like this commit is the culprit:

https://github.com/duckduckgo/duckduckgo-locales/blame/c3d11f15fac2ee1371648c2277f71b0e733a20f7/locales/cs_CZ/LC_MESSAGES/duckduckgo.po#L23

I don't exactly remember, what exactly was the "Czech translation" result of, for example, this previous empty definition:

```
msgid "%s Billion Searches"
msgstr ""
```

... but I would guess that the English version was used prior to this commit, if the Czech version of the `msgstr` was missing (?).

Which was quite fine. _I can assure you that most Czechs understand English a bit more than Danish._ 😸

I might make some time to translate some of the strings to Czech and make PR, but in the meantime I think it would be better if the (previously) missing strings were presented in English instead of Danish.

## Example

![obrazek](https://user-images.githubusercontent.com/6860713/101015411-a5882a00-3567-11eb-9084-c5e5cc3628b0.png)

**Comment by GioSensation** [comment]
Uh! Thanks for spotting this. We'll re-launch the translations and deploy a fix asap. Thanks for your patience.

**Comment by smuuf** [comment]
I noticed the situation got a lot better with commit https://github.com/duckduckgo/duckduckgo-locales/commit/b4a7324fc8f4777f8f3d106a3894a93dab39c699 ... So I guess this issue is pretty much fixed now.

![obrazek](https://user-images.githubusercontent.com/6860713/111866248-74900180-896c-11eb-84a7-0c7754d1670b.png)

Nice. Thanks!
