### ISSUE TITLE
[de_CH] Wrong translation for "Moderate"

### ISSUE THREAD

**Issue by schmandr** [duckduckgo/duckduckgo-locales#438]
In the given context the translation for _Moderate_ should be _Moderat_ rather than _Moderieren_:
https://github.com/duckduckgo/duckduckgo-locales/blob/19749233e7f2892c8093d808e665a13bee75f5cb/locales/de_CH/LC_MESSAGES/duckduckgo.po#L2798-L2804

In `de_DE` it's correct:
https://github.com/duckduckgo/duckduckgo-locales/blob/19749233e7f2892c8093d808e665a13bee75f5cb/locales/de_DE/LC_MESSAGES/duckduckgo.po#L2705-L2711

**Comment by GioSensation** [comment]
This should be fixed now and go out in the next release. Thanks for raising the issue!
