### ISSUE TITLE
Search results in Russian

### ISSUE THREAD

**Issue by ViktorOn** [duckduckgo/duckduckgo-locales#528]
Hi! I don't quite understand how to fix this:
![duck1](https://user-images.githubusercontent.com/63919734/156899205-00335f2b-fa11-4331-882c-542fde280a95.png)
And I would like to make the same quotes « and » in this case:
![duck2](https://user-images.githubusercontent.com/63919734/156899143-2359b197-933c-4aa8-a5b6-ba5eea5144a2.png)
If we can figure this out, I'll be glad :)

**Comment by ViktorOn** [comment]
And here's another moment:
![image](https://user-images.githubusercontent.com/63919734/157453545-f4442d0c-d2b3-4af7-ba14-39ddbc4fb531.png)

**Comment by ViktorOn** [comment]
More fun:
![Duck4](https://user-images.githubusercontent.com/63919734/159361467-0b37d8fd-16db-4461-892f-917e042a7fa6.jpg)

**Comment by ViktorOn** [comment]
> More fun: ![Duck4](https://user-images.githubusercontent.com/63919734/159361467-0b37d8fd-16db-4461-892f-917e042a7fa6.jpg)
It is also inserted into the search with these quotes

**Comment by GioSensation** [comment]
Thanks for the feedback. We've fixed some of this and for the rest it's on the way. 🙂

Note that the use of `"` is a specific syntax you can use to tell our Search Engine to return results that include that specific term. For example if you search for `some "search" term` we will try to show results that include `search`.

Hope it helps, and thanks again for the feedback.

**Comment by ViktorOn** [comment]
I'll raise the topic again :)
![image](https://user-images.githubusercontent.com/63919734/175101160-a287fc48-bf83-4c23-ad96-70812dabeccb.png)
Couldn't find this string...

**Comment by ViktorOn** [comment]
@GioSensation I hope you remember these questions (above)

**Comment by GioSensation** [comment]
@ViktorOn I'm not quite sure what you mean. That string is [here](https://github.com/duckduckgo/duckduckgo-locales/blob/32477d4c87b7fb639b24763820634f058895b80e/locales/ru_RU/LC_MESSAGES/duckduckgo.po#L3506). Feel free to open a PR if you think the translation is wrong. 🙂

**Comment by ViktorOn** [comment]
> @ViktorOn I'm not quite sure what you mean. That string is [here](https://github.com/duckduckgo/duckduckgo-locales/blob/32477d4c87b7fb639b24763820634f058895b80e/locales/ru_RU/LC_MESSAGES/duckduckgo.po#L3506). Feel free to open a PR if you think the translation is wrong. 🙂

You are right about the Open Map string, I did not notice it. But "[Больше Результатов](https://github.com/duckduckgo/duckduckgo-locales/issues/528#issuecomment-1062934744)" I didn't find this string in the .po file.

**Comment by ViktorOn** [comment]
And there is no translation for "[Search in this area](https://github.com/duckduckgo/duckduckgo-locales/blob/32477d4c87b7fb639b24763820634f058895b80e/locales/ru_RU/LC_MESSAGES/duckduckgo.po#L4372)" on an open map:
![image](https://user-images.githubusercontent.com/63919734/179722537-cd3b3136-8c64-433d-8e43-0f39304c0358.png)
