### ISSUE TITLE
Wrong time zone for BRT

### ISSUE THREAD

**Issue by augusto-herrmann** [duckduckgo/duckduckgo-locales#569]
I'm not sure if this should go in the localization repository, but I couldn't find a more specific one to post to. It was posted before as [zeroclickinfo-goodies#4795](https://github.com/duckduckgo/zeroclickinfo-goodies/issues/4795) and closed by @moollaza as completed, but the problem still stands.

> Description
> 
> When querying for time zone conversions, the BRT time zone is considered as if it had daylight savings time. However, daylight savings time has been permanently abolished [by a Decree](https://www.planalto.gov.br/ccivil_03/_Ato2019-2022/2019/Decreto/D9772.htm) in Brazil in 2019.
Steps to recreate
> 
> Search DuckDuckGo for any time zone conversion involving BRT. E.g. "12:00 CET to BRT". You get:
> 
> ![Screenshot 2022-01-18 at 14-27-24 12 00 CET to BRT at DuckDuckGo](https://user-images.githubusercontent.com/1058414/149987842-6d07329b-4430-4620-a7cd-343d61872ecc.png)
> 
> As if BRT was equal to UTC-2, but it is actually UTC-3. So the results are one hour off.
> 
> It might be related to https://github.com/duckduckgo/zeroclickinfo-goodies/issues/4683, since it seems like it is a lack of time zone information maintenance issue (even though the CET zone used in DuckDuckGo seems to be correct at the time of this writing).

Here's a new screenshot taken just now to confirm that the problem still happens:

![timezone-duckduckgo-2022-10-17](https://user-images.githubusercontent.com/1058414/196187982-abaf5eeb-5243-4fa3-9bb5-8add8354b541.png)

Here's the link to a DuckDuckGo search with the wrong instant answer: https://duckduckgo.com/?q=12%3A00+CET+to+BRT&hps=1&atb=v320-1&ia=answer

**Comment by moollaza** [comment]
Thanks for letting us know. The best place to send feedback is using the Feedback button on the DuckDuckGo.com results page. Several staff monitor and read that feedback daily 👍🏽.

We're aware of the DST issues and working to fix them. I'll suggest disabling the Timezone Converter instant answer, until it's corrected.

For now, I'm going to close this issue, as it's irrelevant to the code in this repo.
