### ISSUE TITLE
duckduckgo.com redirects when locale code is longer than two letters

### ISSUE THREAD

**Issue by Siltatano** [duckduckgo/duckduckgo-locales#652]
My apologies if this is not the correct place to post this issue. It is the closest thing I could find.
I usually set my browsers to Asturian (`ast_ES`), and use DuckDuckGo in this language as well. For around two months now, duckduckgo.com has been redirecting to the results page for the query `static/duckduckgo/static-pages/st-ES/home.html`.
It seems the code is being cut short when generating the URL for the redirection: The URL `duckduckgo.com/static/duckduckgo/static-pages/ast-ES/home.html` sends me to the homepage fine, whereas removing the first letter of the code as in `duckduckgo.com/static/duckduckgo/static-pages/st-ES/home.html` leads to the aforementioned search results.
I have checked and this seems to happen to other languages whose code is longer than two letters, such as `ast_ES`, `kab_DZ`, and `tokipona_XX`.

Steps to reproduce:
1. Go to duckduckgo.com
2. Under "All Settings", select "Asturianu". and save changes.
3. Go back to duckduckgo.com, it should redirect to those search results instead of the homepage (refreshing may be needed).

**Comment by GioSensation** [comment]
Thanks for reporting 🙇. I've submitted this to the team and we will look into it 💪.

**Comment by GioSensation** [comment]
This is fixed now. Thank you for reporting.
